swagger: '2.0'
info:
  title: finance
  description: the finance API
  version: 1.0.0
host: localhost
schemes:
  - https
produces:
  - application/json
paths:
  /manage/finance/paymentOrders:
    get:
      tags: [ Finance ]
      summary: 应付单列表
      parameters:
        - name: Authorization
          in: header
          description: 用户认证的token
          type: string
          required: true
        - name: supplierName
          in: query
          description: 供货商名称
          type: string
          required: true
        - name: purchaseNo
          in: query
          description: 采购单号
          type: string
          required: false
        - name: purchaseDateFrom
          in: query
          description: 最早采购日期 yyyy-MM-dd
          type: string
          required: true
        - name: purchaseDateTo
          in: query
          description: 最晚采购日期 yyyy-MM-dd
          type: string
          required: true
        - name: pageIndex
          in: query
          description: 分页位移
          type: integer
          required: false
          default: 0
        - name: pageSize
          in: query
          description: 分页大小
          type: integer
          required: false
          default: 10
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GetPaymentOrdersResp'
  /manage/finance/nettingOrders:
    get:
      tags: [ Finance ]
      summary: 付款申请单列表
      parameters: 
        - name: Authorization
          in: header
          description: 用户认证的token
          type: string
          required: true
        - name: supplierName
          in: query
          description: 收款方（供货商）
          type: string
          required: false
        - name: purchaseNo
          in: query
          description: 采购单号
          type: string
          required: false
        - name: purchaseDateFrom
          in: query
          description: 最早采购日期 yyyy-MM-dd
          type: string
          required: false
        - name: purchaseDateTo
          in: query
          description: 最晚采购日期 yyyy-MM-dd
          type: string
          required: false
        - name: nettingNo
          in: query
          description: 付款申请单号
          type: string
        - name: nettingDateFrom
          in: query
          description: 最早付款申请单日期 yyyy-MM-dd
          type: string
          required: false
        - name: nettingDateTo
          in: query
          description: 最晚付款申请单日期 yyyy-MM-dd
          type: string
          required: false
        - name: status
          in: query
          description: 付款申请单状态 0待审核 1审核不通过 2待支付 3已支付
          type: integer
          required: true
        - name: pageIndex
          in: query
          description: 分页位移
          type: integer
          required: false
          default: 0
        - name: pageSize
          in: query
          description: 分页大小
          type: integer
          required: false
          default: 10
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GetNettingOrdersResp'
    post:
      tags: [ Finance ]
      summary: 新建付款申请单
      parameters:
        - name: Authorization
          in: header
          description: 用户认证的token
          type: string
          required: true
        - name: nettingOrderParam
          in: body
          description: The nettingOrder to create.
          required: true
          schema:
            $ref: '#/definitions/PostNettingOrdersParam'
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/PostNettingOrdersResp'
  /manage/finance/nettingOrders/{id}:
    get:
      tags: [ Finance ]
      summary: 根据id查付款申请单
      parameters:
        - name: Authorization
          in: header
          description: 用户认证的token
          type: string
          required: true
        - name: id
          in: path
          description: 付款申请单id
          type: integer
          format: int64
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/GetNettingOrderInfoResp'
  /manage/finance/nettingOrders/{id}/payment:
    post:
      tags: [ Finance ]
      summary: 付款申请单确认付款
      parameters:
        - name: Authorization
          in: header
          description: 用户认证的token
          type: string
          required: true
        - name: id
          in: path
          description: 付款申请单id
          type: integer
          format: int64
          required: true
        - name: nettingOrderParam
          in: body
          description: The nettingOrder to create.
          required: true
          schema:
            $ref: '#/definitions/PostNettingOrdersPaymentParam'
      responses:
        '200':
          description: OK
          schema:
              $ref: '#/definitions/CommonResp'
  /manage/finance/nettingOrders/batch:
    post:
      tags: [ Finance ]
      summary: 批量更新付款申请单
      parameters:
        - name: Authorization
          in: header
          description: 用户认证的token
          type: string
          required: true
        - name: nettingOrdersByBatchParam
          in: body
          description: The nettingOrder to update by batch.
          required: true
          schema:
            $ref: '#/definitions/PostNettingOrdersByBatchParam'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CommonResp'
  /manage/finance/nettingOrders/excelExport:
    get:
      tags: [ Finance ]
      summary: 付款申请单列表excel导出
      parameters: 
        - name: token
          in: query
          description: 用户认证的token
          type: string
          required: false
        - name: supplierName
          in: query
          description: 收款方（供货商）
          type: string
          required: false
        - name: purchaseNo
          in: query
          description: 采购单号
          type: string
          required: false
        - name: purchaseDateFrom
          in: query
          description: 最早采购日期 yyyy-MM-dd
          type: string
          required: false
        - name: purchaseDateTo
          in: query
          description: 最晚采购日期 yyyy-MM-dd
          type: string
          required: false
        - name: nettingNo
          in: query
          description: 付款申请单号
          type: string
        - name: nettingDateFrom
          in: query
          description: 最早付款申请单日期 yyyy-MM-dd
          type: string
          required: false
        - name: nettingDateTo
          in: query
          description: 最晚付款申请单日期 yyyy-MM-dd
          type: string
          required: false
        - name: status
          in: query
          description: 付款申请单状态 0待审核 1审核不通过 2待支付 3已支付
          type: integer
          required: false
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CommonResp'
definitions:
  GetPaymentOrderData:
    type: object
    properties:
      supplierId:
        type: integer
        format: int64
        description: 供货商id
      supplierName:
        type: string
        description: 供货商名称
      bankName:
        type: string
        description: 收款银行
      bankAccount:
        type: string
        description: 收款账号
      purchaseNo:
        type: string
        description: 采购单号
      purchaseAmount:
        type: string
        description: 采购单金额
      purchaseDate:
        type: string
        description: 采购日期 yyyy-MM-dd
      paymentId:
        type: integer
        format: int64
        description: 应付单id
      paymentNo: 
        type: string
        description: 应付单号
      paymentDate:
        type: string
        description: 应付日期
      paymentAmount:
        type: string
        description: 应付金额
      paymentRealAmount:
        type: string
        description: 本次应付金额
      isInstallment:
        type: integer
        description: 是否分期付款 0:不是 1:是
  GetPaymentOrdersData:
    type: object
    properties:
      paymentOrders:
        type: array
        items:
          $ref: '#/definitions/GetPaymentOrderData'
      totalSize:
        type: integer
        description: 未生成付款申请单的应付款单总条数
  GetPaymentOrdersResp:
    type: object
    properties:
      code:
        type: integer
        description: 0表示成功
      info: 
        type: string
        description: code为0时，显示success，code不为0时，显示错误信息
      data:
        $ref: '#/definitions/GetPaymentOrdersData'
  GetNettingOrderData:
    type: object
    properties:
      nettingId:
        type: integer
        format: int64
        description: 付款申请单id
      nettingNo:
        type: string
        description: 付款申请单号
      supplierName:
        type: string
        description: 收款人
      nettingDate:
        type: string
        description: 付款申请单生成日期 yyyy-MM-dd
      nettingAmount:
        type: string
        description: 付款申请单金额
      invoiceCodeNo:
        type: string
        description: 发票代码+发票号
      invoiceAmount:
        type: string
        description: 发票金额
      taxAmount:
        type: string
        description: 税额
      status:
        type: integer
        description: 付款申请单状态 0待审核 1审核不通过 2待支付 3已支付
      paidDate:
        type: string
        description: 付款申请单支付日期
      payor:
        type: string
        description: 付款人
      paymentFlowNo:
        type: string
        description: 付款流水号
  GetNettingOrdersData:
    type: object
    properties:
      nettingOrders:
        type: array
        items:
          $ref: '#/definitions/GetNettingOrderData'
      totalSize:
        type: integer
        description: 应付款单总条数
  GetNettingOrdersResp:
    type: object
    properties:
      code:
        type: integer
        description: 0表示成功
      info: 
        type: string
        description: code为0时，显示success，code不为0时，显示错误信息
      data:
        $ref: '#/definitions/GetNettingOrdersData'
  PostNettingOrdersData:
    type: object
    properties:
      nettingNo:
        type: string
        description: 付款申请单号
      createDate:
        type: string
        description: 付款申请单生成日期 yyyy-MM-dd
      nettingAmount:
        type: string
        description: 付款申请单金额
  PostNettingOrdersResp:
      type: object
      properties:
        code:
          type: integer
          description: 0表示成功
        info: 
          type: string
          description: code为0时，显示success，code不为0时，显示错误信息
        data:
          $ref: '#/definitions/PostNettingOrdersData'
  PostNettingOrdersByBatchParam:
    type: object
    properties:
      auditStatus:
        type: integer
        description: 审核状态 0不通过 1通过
      auditInfo:
        type: string
        description: 审核信息
      nettingIds:
        type: array
        items:
          type: integer
          format: int64
  PostNettingOrdersParam:
    properties:
      supplierId:
        type: integer
        format: int64
        description: 供货商id
      supplierName:
        type: string
        description: 供货商名字
      invoiceCode:
        type: string
        description: 发票代码
      invoiceNo:
        type: string
        description: 发票号
      invoiceAmount:
        type: string
        description: 发票金额
      invoiceDate:
        type: string
        description: 开票日期
      taxRate:
        type: string
        description: 税率
      taxAmount:
        type: string
        description: 税额
      paymentOrders:
        type: array
        items:
          $ref: '#/definitions/PostNettingOrdersItemParam'
  PostNettingOrdersItemParam:
    type: object
    properties:
      paymentId:
        type: integer
        format: int64
        description: 应付单id
      paymentRealAmount:
        type: string
        description: 本次应付金额
  PostNettingOrdersPaymentParam:
    properties:
      payorBankName:
        type: string
        description: 付款人开户银行
      payorBankAccount:
        type: string
        description: 付款人银行账号
      payorName:
        type: string
        description: 付款人
      paidDate:
        type: string
        description: 付款日期
      paymentFlowNo:
        type: string
        description: 付款流水号
  GetNettingOrderInfoData:
    type: object
    properties:
      nettingOrderMaker:
        type: string
        description: 制单人（对应用户名）
      supplierName:
        type: string
        description: 供货商名称
      nettingNo:
        type: string
        description: 付款申请单号
      nettingDate:
        type: string
        description: 付款申请单创建时间 yyyy-MM-dd
      nettingStatus:
        type: integer
        description: 付款申请单状态 0待审核 1审核不通过 2待支付 3已支付
      nettingAmount:
        type: string
        description: 付款申请单金额
      payeeBankName:
        type: string
        description: 收款人银行
      payeeBankAccount:
        type: string
        description: 收款人银行账户
      invoiceCodeNo:
        type: string
        description: 发票代码 + 发票号
      invoiceAmount:
        type: string
        description: 发票金额
      taxAmount:
        type: string
        description: 税额
      taxRate:
        type: string
        description: 税率
      paymentOrders:
        type: array
        items:
          $ref: '#/definitions/GetPaymentOrderData'
  GetNettingOrderInfoResp:
      type: object
      properties:
        code:
          type: integer
          description: 0表示成功
        info: 
          type: string
          description: code为0时，显示success，code不为0时，显示错误信息
        data:
          $ref: '#/definitions/GetNettingOrderInfoData'
  CommonResp:
    type: object
    properties:
      code:
        type: integer
        description: 0表示成功
      info: 
        type: string
        description: code为0时，显示success，code不为0时，显示错误信息
      data:
        type: object
        description: data
      